// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;   // Defined in arduino_secrets.h
const char PASS[]     = SECRET_PASS;   // Defined in arduino_secrets.h



void initProperties(){




}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
